### PR TITLE
Fallback to plain if json data is not a hash map

### PR DESCRIPTION
**Pull request by nabam**
Should fix https://github.com/logstash-plugins/logstash-input-file/issues/18

### CODE REVIEW

**Comment by nabam** [comment]
@ycombinator @ph

**Comment by suyograo** [comment]
@guyboertje can you review this please?

**Comment by suyograo** [comment]
@nabam can you please perform step 2 of https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by suyograo** [comment]
@nabam also, you need to rebase since @andrewvc fixed an issue in this file recently

**Comment by nabam** [comment]
@suyograo done with step 2. Of course it needs to be rebased, pull request is opened almost for 4 months

**Comment by andrewvc** [comment]
Apologies for the delay @nabam , I have a more full fix here in #14 that should handle even more scenarios. I'd love your input in that ticket regarding how logstash should handle scalar values (string / number)

**Pull request closed without merging**
